name: pval
description: run Pval TP

inputs:
      runDir: 
          description: "runDir path"
          required: true

runs:
      using: "composite"
      
      steps:
        - name: print PVal path
          run:  echo  $env:pValPath   
          shell: powershell
        - name: List mapped drives
          run:  net use
          shell: powershell
        - name: Map I:drive 
          run:  'net use I: \\amr.corp.intel.com\ec\proj\mdl\jf\intel /y ; $LASTEXITCODE= 0'
          shell: powershell
        - name: change folder
          #run:  Set-Location -Path ${{inputs.runDir}}  
          run:  Set-Location -Path C:\runDir -PassThru
          shell: powershell          
        - name: Run pVal
          run:  powershell .\pipeline_scripts\pVal\PrimeValTool.exe $env:tosPath full -sk
          shell: powershell
       
