name: coverage
description: unittest coverage
runs:
      using: "composite"
      
      steps:
        - name: List mapped drives
          run:  net use
          shell: powershell
        - name: Map I:drive 
          run:  'net use I: \\amr.corp.intel.com\ec\proj\mdl\jf\intel /y ; $LASTEXITCODE= 0'
          shell: powershell
        - name: Run pVal
          run:  powershell $env:pValPath $env:tosPath full -sk
          shell: powershell
