name: release
description: run release scripts

inputs:
      authkey: 
          description: "repo authentication key"
          required: true
      runDir: 
          description: "runDir path"
          required: true

runs:
      using: "composite"

      steps:
        - name: Print current repo ref
          run: echo $env:GITHUB_REF_NAME     
          shell: powershell
        - name: Run DocParser
          run: ${{inputs.runDir}}\pipeline_scripts\DocParser.py
          shell: powershell
        - name: Run wiki_builder.py
          run: ${{inputs.runDir}}\pipeline_scripts\wiki_builder.py -authkey ${{inputs.authkey}}
          shell: powershell
        - name: Sleep for 30 seconds
          run: Start-Sleep -s 30
          shell: powershell
        - name: Run CopyFolder.cmd
          run: ${{inputs.runDir}}\pipeline_scripts\CopyFolder.cmd $env:GITHUB_REF_NAME
          shell: powershell
        - name: Run emailRelease.exe
          run: ${{inputs.runDir}}\pipeline_scripts\emailRelease.exe
          shell: powershell
