name: compile
description: compile code

inputs:
      runDir: 
          description: "runDir path"
          required: true

runs:
      using: "composite"
   
      steps:
      - name: restore
        run:  "dotnet tool restore"
        shell: powershell
      - name: compile base
        run:  ${{inputs.runDir}}\pipeline_scripts\CompileAll.cmd Base -ci $env:GITHUB_WORKSPACE
        shell: powershell
      - name: compile target
        run:  ${{inputs.runDir}}\pipeline_scripts\CompileAll.cmd $env:TARGET -ci $env:GITHUB_WORKSPACE
        shell: powershell
      - name: print GITHUB_WORKSPACE
        run:  powershell "echo $env:GITHUB_WORKSPACE"
        shell: powershell
